### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jackniklason** [KwatME/sea#1]
<img width="697" alt="Screen Shot 2021-01-06 at 2 16 45 PM" src="https://user-images.githubusercontent.com/50241841/103820594-e1605480-5029-11eb-82c8-44e7e8988a8c.png">

**Comment by KwatME** [comment]
Fixed. Can you try it again?

**Comment by jackniklason** [comment]
working now thanks

**Comment by KwatME** [comment]
You should be able to run the notebook.
Meanwhile, I'm making individual functions (.py files based on the functions I defined in the notebook cells).
